### ISSUE TITLE
Platforms Theme not showing the platforms

### ISSUE THREAD

**Issue by DanielMMend** [davidkgriggs/Platforms#6]
Hello.
Thanks for your quick reply at my last "Issue Report".

I was now able to instal the "Platforms" Theme, however it is not showing the platforms of the games, as I'm goint to show you.

Here is my Playnite:
![Screenshot_2](https://user-images.githubusercontent.com/101355852/198848446-b5c7b14c-9bec-4310-9545-adc25400b329.png)

And here is how it should look, acording to the images of the "Platforms" Theme that you have uploaded here:
![Screenshot_3](https://user-images.githubusercontent.com/101355852/198848467-c0cfebd9-6c3f-40de-a151-945b4f002a6b.png)

I only have 2 games now at Playnite, just to test the application... But one of them is a SNES game, and the other one is a Steam game for Windows... And neither of the platforms are showed on the Top Menu

**Comment by davidkgriggs** [comment]
That's driven by a feature of Playnite itself called Filter Presets. You need to create Filter Presets and name them to match what is in the wiki of this theme.
